" Vim-Plug plugins 
call plug#begin('~/.vim/plugged')
"Plug 'tpope/vim-fugitive'
Plug 'scrooloose/nerdtree'
"Plug 'kaicataldo/material.vim'
"Plug 'itchyny/lightline.vim'
Plug 'Xuyuanp/nerdtree-git-plugin'
"Plug 'jiangmiao/auto-pairs'
"Plug 'airblade/vim-gitgutter'
"Plug 'lifepillar/vim-solarized8'
Plug 'altercation/vim-colors-solarized'
Plug 'tpope/vim-surround'
Plug 'kien/ctrlp.vim'
"Plug 'ternjs/tern_for_vim', { 'do' : 'npm install' }
Plug 'valloric/youcompleteme'
Plug 'vim-syntastic/syntastic'
"Plug 'vim-airline/vim-airline'
"Plug 'vim-airline/vim-airline-themes'
Plug 'morhetz/gruvbox'
call plug#end()

" Setting up a seperate directory for vim swap files
set swapfile
set dir=~/.vim/vimSwapFiles

" Syntastic recommended settings
"set statusline+=%#warningmsg#
"set statusline+=%{SyntasticStatuslineFlag()}
"set statusline+=%*

" Other syntastic settings
"let g:syntastic_python_python_exec = 'python3'

" let g:syntastic_always_populate_loc_list = 1
" let g:syntastic_auto_loc_list = 1
" let g:syntastic_check_on_open = 1
" let g:syntastic_check_on_wq = 0

" Airline setting
"let g:airline_theme='solarized'
"let g:airline#extensions#tabline#enabled = 1
"let g:airline_solarized_normal_green = 1
"let g:airline_powerline_fonts = 1

" Lightline settings
"let g:lightline = {
"      \ 'colorscheme': 'solarized',
"      \ }
"let g:material_theme_style = 'dark'

" Disabling CtrlP switching to the nearest .git
let g:ctrlp_working_path_mode = 0 

" Ignore some folders and files for CtrlP indexing
let g:ctrlp_custom_ignore = {
  \ 'dir':  '\.git$\|\.yardoc\|node_modules\|log\|tmp$',
  \ 'file': '\.so$\|\.dat$|\.DS_Store$'
\ }

"set number
set relativenumber
syntax on
set background=dark
"set background=light
colorscheme gruvbox

" To avoid needing to save before switching buffers
set hidden

" Tab spaces fix
set tabstop=4       " The width of a TAB is set to 4.
                    " Still it is a \t. It is just that
                    " Vim will interpret it to be having
                    " a width of 4.
set shiftwidth=4    " Indents will have a width of 4
set softtabstop=4   " Sets the number of columns for a TAB
set expandtab       " Expand TABs to spaces

set laststatus=2 " Lightline fix

" Open splits to the right and bottom
set splitbelow
set splitright

" Mappings
nmap <F6> :NERDTreeToggle<CR>
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

"Based on Vim patch 7.4.1770 (`guicolors` option) < https://github.com/vim/vim/commit/8a633e3427b47286869aa4b96f2bfc1fe65b25cd >
" < https://github.com/neovim/neovim/wiki/Following-HEAD#20160511 >
if (has("termguicolors"))
    set termguicolors
endif

" --AUTOCOMPLETION--
"filetype plugin on
"set omnifunc=syntaxcomplete#Complete

" Color of youcompleteme
highlight Pmenu ctermfg=2 ctermbg=3 guifg=#154360 guibg=#85c1e9
highlight PmenuSel ctermfg=2 ctermbg=3 guifg=#ffffff guibg=#0000ff

" Use the find command recursively 
set path=.,/usr/include,,**

" Enable folding
set foldmethod=indent
set foldlevel=99

" Highlight searches
set hlsearch
